"""Chirag Model Router - Capability Contract, Router, Executor, Providers, and Evaluation Contract (M3.7)."""


from .analyzer import analyze_execution_plan
from .evaluation import (
    EvaluationCandidate,
    EvaluationDimension,
    EvaluationError,
    EvaluationResult,
    EvaluationScore,
    EvaluationStatus,
    EvaluationSummary,
    EvaluationTask,
    InvalidEvaluationCandidateError,
    InvalidEvaluationDimensionError,
    InvalidEvaluationResultError,
    InvalidEvaluationScoreError,
    InvalidEvaluationSummaryError,
    InvalidEvaluationTaskError,
    build_evaluation_summary,
    evaluation_result_from_model_result,
    rank_scores,
    select_winner,
    validate_evaluation_candidate,
    validate_evaluation_dimension,
    validate_evaluation_result,
    validate_evaluation_score,
    validate_evaluation_summary,
    validate_evaluation_task,
)
from .executor import MockModelExecutor, ModelExecutor
from .local_executor import (
    DeterministicLocalBackend,
    InProcessBackend,
    LocalBackendResult,
    LocalModelBackend,
    LocalModelExecutor,
)
from .providers import (
    LocalModelProvider,
    ModelProvider,
    OpenRouterClient,
    OpenRouterConfig,
    OpenRouterProvider,
    ProviderHealth,
    ProviderRegistry,
    ProviderStatus,
)
from .registry import ModelRegistry
from .routed_executor import RoutedModelExecutor
from .router import ModelRouter
from .schema import (
    ExecutionPlan,
    ExecutionStatus,
    Modality,
    ModelCapability,
    ModelExecutionRequest,
    ModelRequirements,
    ModelResult,
    ModelSelection,
    PlanStep,
    RegisteredModel,
)
from .validation import (
    DuplicateModelError,
    DuplicateProviderError,
    ExecutionError,
    ModelNotFoundError,
    NoCompatibleModelError,
    ProviderError,
    ProviderExecutionError,
    ProviderNotFoundError,
    RoutingError,
    sanitize_error_message,
    validate_execution_plan_for_routing,
    validate_execution_request,
    validate_model_requirements,
    validate_model_result,
    validate_registered_model,
)

__all__ = [
    "ModelCapability",
    "Modality",
    "ExecutionStatus",
    "ProviderStatus",
    "ProviderHealth",
    "ModelRequirements",
    "RegisteredModel",
    "ModelSelection",
    "ModelExecutionRequest",
    "ModelResult",
    "PlanStep",
    "ExecutionPlan",
    "ModelRegistry",
    "ModelRouter",
    "ModelExecutor",
    "MockModelExecutor",
    "LocalModelExecutor",
    "LocalModelBackend",
    "InProcessBackend",
    "DeterministicLocalBackend",
    "LocalBackendResult",
    "ModelProvider",
    "ProviderRegistry",
    "LocalModelProvider",
    "OpenRouterProvider",
    "OpenRouterConfig",
    "OpenRouterClient",
    "RoutedModelExecutor",
    "RoutingError",
    "NoCompatibleModelError",
    "DuplicateModelError",
    "ModelNotFoundError",
    "ExecutionError",
    "ProviderError",
    "DuplicateProviderError",
    "ProviderNotFoundError",
    "ProviderExecutionError",
    "sanitize_error_message",
    "analyze_execution_plan",
    "validate_model_requirements",
    "validate_execution_plan_for_routing",
    "validate_registered_model",
    "validate_execution_request",
    "validate_model_result",
    "EvaluationStatus",
    "EvaluationTask",
    "EvaluationCandidate",
    "EvaluationResult",
    "EvaluationDimension",
    "EvaluationScore",
    "EvaluationSummary",
    "EvaluationError",
    "InvalidEvaluationTaskError",
    "InvalidEvaluationCandidateError",
    "InvalidEvaluationResultError",
    "InvalidEvaluationDimensionError",
    "InvalidEvaluationScoreError",
    "InvalidEvaluationSummaryError",
    "validate_evaluation_task",
    "validate_evaluation_candidate",
    "validate_evaluation_result",
    "validate_evaluation_dimension",
    "validate_evaluation_score",
    "validate_evaluation_summary",
    "rank_scores",
    "select_winner",
    "build_evaluation_summary",
    "evaluation_result_from_model_result",
]
